#if !os(macOS)
import XCTest

extension ContainerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContainerTests = [
        ("testFirst", testFirst),
        ("testInit", testInit),
        ("testInsert", testInsert),
        ("testRemove", testRemove),
        ("testSelect", testSelect),
        ("testUpdate", testUpdate),
    ]
}

extension StorageTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageTests = [
        ("testClassType", testClassType),
        ("testInit", testInit),
        ("testRecovery", testRecovery),
        ("testSnapshot", testSnapshot),
        ("testStorage", testStorage),
        ("testStoragePersistence", testStoragePersistence),
    ]
}

extension WALTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WALTests = [
        ("testInit", testInit),
        ("testRestore", testRestore),
        ("testWrite", testWrite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ContainerTests.__allTests__ContainerTests),
        testCase(StorageTests.__allTests__StorageTests),
        testCase(WALTests.__allTests__WALTests),
    ]
}
#endif
