#if !os(macOS)
import XCTest

extension BinaryServerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryServerTests = [
        ("testBinaryProtocol", testBinaryProtocol),
    ]
}

extension HTTPServerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPServerTests = [
        ("testHTTPFullStask", testHTTPFullStask),
        ("testHTTPHandler", testHTTPHandler),
    ]
}

extension ServerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ServerTests = [
        ("testServer", testServer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryServerTests.__allTests__BinaryServerTests),
        testCase(HTTPServerTests.__allTests__HTTPServerTests),
        testCase(ServerTests.__allTests__ServerTests),
    ]
}
#endif
